### ISSUE TITLE
mae criterion is very slow compared to mse or friedman_mse for classification

### ISSUE THREAD

**Issue by flamby** [fabsig/KTBoost#2]
Hello,

I did some bench w/ the 3 criterions available for classification, and mae is at least one order of magnitude slower. any reason?

```
model = KTBoost.BoostingClassifier(loss='deviance',update_step='hybrid', criterion='mae',
                                   n_estimators=50, random_state=seed)
model.fit(X_train,y_train)
probas = model.predict_proba(X_test) 
```

**Comment by fabsig** [comment]
I guess that this is simply due to the fact that building regression trees with the 'mae' criterion is slower than with the other ones ('mse' or 'friedman_mse') for which there are fast version. I must admit though, that I am not an expert concerning regression trees with the MAE criterion.
