### ISSUE TITLE
Implement non-constant learning rates

### ISSUE THREAD

**Issue by lorenzwalthert** [fabsig/KTBoost#4]
Could it be interesting to have decaying or even oscillating learning rates, as it is common for deep learning? Have never seen it for boosted trees but might be worth exploring. See allso https://github.com/lorenzwalthert/KerasMisc.

**Comment by fabsig** [comment]
This could be interesting. However, before we implement something like this, it first needs to be investigated whether this is beneficial for boosting. To my knowledge, there are not results on this.
