### ISSUE TITLE
sample_weight is being multiplied twice -  Tobit Loss

### ISSUE THREAD

**Issue by sanketrdeshmukh** [fabsig/KTBoost#6]
In the negative gradient of the tobit loss function, residual accounts for the sample_weight for each observation. In addition to that, sample weight is being accounted for again in the leaf update step.  There might double accounting for sample weights for the tobit update step.

Whereas all the other loss functions account for sample weight only in the leaf update step.

**Comment by fabsig** [comment]
Many thanks for your comment, sanketrdeshmukh!

Can you please refer to the exact locations in the code, this makes it easier for me to check this.

**Comment by sanketrdeshmukh** [comment]
The first time sample weights are used at: https://github.com/fabsig/KTBoost/blob/df79c8152f1b706d221d16526577f8acc4ca1e84/KTBoost/KTBoost.py#L748

and then second time here at
https://github.com/fabsig/KTBoost/blob/df79c8152f1b706d221d16526577f8acc4ca1e84/KTBoost/KTBoost.py#L811

**Comment by fabsig** [comment]
Yes, you are right. I have corrected this. 

Thanks for pointing this out!
