### ISSUE TITLE
Compatibility with scikit-learn 0.24.0 

### ISSUE THREAD

**Issue by davidlkl** [fabsig/KTBoost#9]
I am using KTBoost 0.1.19 and got the following error:

Traceback (most recent call last):

  File "train_model.py", line 135, in <module>
    ktb_regressor.fit(X_train_cv, y_train_cv)

  File "C:\ProgramData\Anaconda3\lib\site-packages\KTBoost\KTBoost.py", line 1755, in fit
    n_stages = self._fit_stages(X, y, y_pred, sample_weight, self._rng,

  File "C:\ProgramData\Anaconda3\lib\site-packages\KTBoost\KTBoost.py", line 1820, in _fit_stages
    y_pred = self._fit_stage(i, X, y, y_pred, sample_weight,

  File "C:\ProgramData\Anaconda3\lib\site-packages\KTBoost\KTBoost.py", line 1361, in _fit_stage
    tree.fit(X, residual, sample_weight=weights,

  File "C:\ProgramData\Anaconda3\lib\site-packages\KTBoost\tree.py", line 1130, in fit
    super(DecisionTreeRegressor, self).fit(

  File "C:\ProgramData\Anaconda3\lib\site-packages\KTBoost\tree.py", line 368, in fit
    builder.build(self.tree_, X, y, sample_weight, X_idx_sorted)

  File "sklearn\tree\_tree.pyx", line 136, in sklearn.tree._tree.DepthFirstTreeBuilder.build

TypeError: build() takes at most 4 positional arguments (5 given)

Thanks in advance!

**Comment by fabsig** [comment]
Thanks for letting me know! 

This should be fixed now with the new version 0.1.20 of KTBoost.

**Comment by davidlkl** [comment]
Wow that's quick! I have explored this library a bit and found this approach provides better performance than other famous counterparts like XGBoost.

Having said that, I suspect I could have more performance gain by playing with the loss function. My target variable is following a zero-inflated log-normal / zero-inflated gamma, so I think using a tweedie deviance as loss function should be more appropriate. I tried Tobit loss but my zeros are in very high fraction (>.8) so the truncated normality assumption does not work well. 

I am looking at how to define a custom loss, but it seems that apart from defining the loss, I would also need to work with the _update_terminal_region, which is not very familiar to me.

Would you have time to look into this? Or is there any doc that would be useful for this?

Thanks!

**Comment by fabsig** [comment]
Thanks for your feedback. I agree with your assessment that other discrete-continuous losses, apart from the Tobit loss, can lead to better performances.

Yes, you are right about what needs to be done in terms of coding for implementing other losses. Unfortunately, I don't have any docs for this. But the structure is the same as in scikit-learn.

For what type of application do you plan to use this? We might collaborate on this. If this is an option, send me an e-mail.

**Comment by davidlkl** [comment]
The application is to model claims, for a Kaggle-like competition.

After spending some time reading the code, I find the function update_terminal_region is most of the time making a single Newton-Raphson step only. I think the implementation of tweedie loss should be similar to poisson loss, I will give it a try and make a pull request later.

Thanks!
